version: '3.8'

services:
  db:
    image: postgres:15
    container_name: protheus-db
    restart: always
    environment:
      POSTGRES_DB: protheuslexicon
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  #backend:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: protheus-backend
  #  depends_on:
  #    - db
  #  environment:
   #   SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/protheuslexicon
  #    SPRING_DATASOURCE_USERNAME: admin
  #    SPRING_DATASOURCE_PASSWORD: admin
  #    SPRING_PROFILES_ACTIVE: ci
  #  ports:
  #    - "8080:8080"

volumes:
  pgdata:
