spring:
  datasource:
    url: jdbc:h2:mem:testdb  # Usa um banco em memória para testes
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none  # Evita a criação automática de tabelas
  sql:
    init:
      mode: never
